#!/usr/bin/env tsx

/**
 * Git hooks # Run TypeScript linting script for staged files
lint_output=$(npm run lint:prose:staged --silent 2>&1)
vale_exit_code=$?e Web Portfolio project
 *
 * This script generates git hooks and installs them in the .git/hooks directory.
 * It ensures hooks are executable and properly configured for the project.
 *
 * Key benefits:
 * - Version-controlled hook logic (unlike .git/hooks which aren't tracked)
 * - Automatic installation via npm postinstall
 * - Cross-platform compatibility
 * - Easy to modify and extend
 *
 * Usage:
 *   npm run setup-hooks        # Manual installation
 *   npm install               # Automatic installation via postinstall
 *
 * The hooks are written in shell script for maximum git compatibility,
 * but generated from TypeScript for maintainability.
 */

import { writeFileSync, chmodSync, existsSync, mkdirSync } from "fs";
import { join } from "path";

const PROJECT_ROOT = process.cwd();
const HOOKS_DIR = join(PROJECT_ROOT, ".git", "hooks");

/**
 * Pre-commit hook that runs Vale linting on staged Markdown files
 */
const PRE_COMMIT_HOOK = `#!/bin/sh
#
# Pre-commit hook to run Vale linting on staged Markdown files
# Generated by scripts/setup-git-hooks.ts - do not edit manually
#

echo "Running Vale linting on staged Markdown files..."

# Get list of staged .md files in source/site/content
staged_md_files=$(git diff --cached --name-only --diff-filter=ACM | grep '^source/site/content/.*\\.md$')

if [ -z "$staged_md_files" ]; then
    echo "No staged Markdown files in source/site/content to lint."
    exit 0
fi

echo "Linting files:"
echo "$staged_md_files"

# Run TypeScript linting script for staged files
lint_output=$(npm run lint:prose:staged --silent 2>&1)
vale_exit_code=$?

if [ $vale_exit_code -ne 0 ]; then
    echo ""
    echo "$lint_output"
    echo ""
    echo "You can fix these issues or commit anyway."
    echo "To skip this check, use: git commit --no-verify"
    echo ""
    
    # Ask user if they want to proceed
    echo "Do you want to commit anyway? (y/N)"
    read -r response
    case $response in
        [yY][eS]|[yY]) 
            echo "Proceeding with commit..."
            exit 0
            ;;
        *)
            echo "Commit aborted. Fix the issues or use --no-verify to skip."
            exit 1
            ;;
    esac
else
    echo "$lint_output"
fi

exit 0`;

/**
 * Hook configurations
 */
const HOOKS = {
  "pre-commit": {
    content: PRE_COMMIT_HOOK,
    description: "Vale linting for Markdown content",
  },
};

/**
 * Ensure the hooks directory exists
 */
function ensureHooksDirectory(): void {
  if (!existsSync(HOOKS_DIR)) {
    console.log(
      "⚠️  .git/hooks directory not found. Make sure you are in a git repository."
    );
    process.exit(1);
  }
}

/**
 * Install a git hook
 */
function installHook(
  name: string,
  config: { content: string; description: string }
): void {
  const hookPath = join(HOOKS_DIR, name);

  try {
    // Write the hook file
    writeFileSync(hookPath, config.content, { encoding: "utf8" });

    // Make it executable
    chmodSync(hookPath, 0o755);

    console.log(`✅ Installed ${name} hook: ${config.description}`);
  } catch (error) {
    console.error(`❌ Failed to install ${name} hook:`, error);
    process.exit(1);
  }
}

/**
 * Main function
 */
function main(): void {
  console.log("🔧 Setting up git hooks for Web Portfolio...\n");

  // Ensure we're in a git repository
  ensureHooksDirectory();

  // Install all hooks
  let installedCount = 0;
  for (const [name, config] of Object.entries(HOOKS)) {
    installHook(name, config);
    installedCount++;
  }

  console.log(
    `\n🎉 Successfully installed ${installedCount} git hook(s)!`
  );
  console.log("\nHooks installed:");

  for (const [name, config] of Object.entries(HOOKS)) {
    console.log(`  • ${name}: ${config.description}`);
  }

  console.log("\n💡 Tips:");
  console.log(
    '  • Use "git commit --no-verify" to skip hooks if needed'
  );
  console.log(
    '  • Run "npm run setup-hooks" to reinstall hooks after git operations'
  );
  console.log(
    "  • Hooks are generated from scripts/setup-git-hooks.ts"
  );
}

// Run the script
if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}

export { main as setupGitHooks };
