import { execSync } from "node:child_process";
import { existsSync } from "node:fs";
import { join, relative } from "node:path";
import { BuildLogger } from "./helpers.js";

/**
 * Git utilities for detecting changed files and repository status
 */
export class GitUtils {
  private static isGitRepo: boolean | null = null;

  /**
   * Check if the current directory is a git repository
   */
  static isGitRepository(): boolean {
    if (this.isGitRepo !== null) {
      return this.isGitRepo;
    }

    try {
      execSync("git rev-parse --git-dir", { stdio: "ignore" });
      this.isGitRepo = true;
      return true;
    } catch {
      this.isGitRepo = false;
      return false;
    }
  }

  /**
   * Get the current git branch name
   */
  static getCurrentBranch(): string | null {
    if (!this.isGitRepository()) {
      return null;
    }

    try {
      const branch = execSync("git branch --show-current", {
        encoding: "utf8",
        stdio: ["ignore", "pipe", "ignore"],
      }).trim();
      return branch || null;
    } catch {
      return null;
    }
  }

  /**
   * Get files that have been modified, added, or renamed since the last commit
   * This includes both staged and unstaged changes
   */
  static getChangedFiles(): string[] {
    if (!this.isGitRepository()) {
      BuildLogger.warn("Not a git repository - cannot detect changed files");
      return [];
    }

    try {
      // Get staged changes
      const stagedOutput = execSync("git diff --cached --name-only", {
        encoding: "utf8",
        stdio: ["ignore", "pipe", "ignore"],
      }).trim();

      // Get unstaged changes
      const unstagedOutput = execSync("git diff --name-only", {
        encoding: "utf8",
        stdio: ["ignore", "pipe", "ignore"],
      }).trim();

      // Get untracked files
      const untrackedOutput = execSync(
        "git ls-files --others --exclude-standard",
        {
          encoding: "utf8",
          stdio: ["ignore", "pipe", "ignore"],
        }
      ).trim();

      const changedFiles = new Set<string>();

      // Add staged files
      if (stagedOutput) {
        stagedOutput
          .split("\n")
          .forEach((file) => changedFiles.add(file.trim()));
      }

      // Add unstaged files
      if (unstagedOutput) {
        unstagedOutput
          .split("\n")
          .forEach((file) => changedFiles.add(file.trim()));
      }

      // Add untracked files
      if (untrackedOutput) {
        untrackedOutput
          .split("\n")
          .forEach((file) => changedFiles.add(file.trim()));
      }

      return Array.from(changedFiles).filter((file) => file.length > 0);
    } catch (error) {
      BuildLogger.error(`Failed to get changed files: ${error}`);
      return [];
    }
  }

  /**
   * Get markdown files that have changed since the last commit
   * Filters the changed files to only include .md files in the content directory
   */
  static getChangedMarkdownFiles(
    contentDirectory: string = "source/site/content/published"
  ): string[] {
    return this.getChangedMarkdownPaths(contentDirectory).filter((filePath) =>
      existsSync(filePath)
    );
  }

  /**
   * Get markdown paths that have changed since the last commit.
   * Includes deleted paths so incremental invalidation can rebuild related outputs.
   */
  static getChangedMarkdownPaths(
    contentDirectory: string = "source/site/content/published"
  ): string[] {
    const changedFiles = this.getChangedFiles();
    const changedMarkdownPaths: string[] = [];

    for (const file of changedFiles) {
      if (file.endsWith(".md") && file.startsWith(contentDirectory)) {
        changedMarkdownPaths.push(join(process.cwd(), file));
      }
    }

    return changedMarkdownPaths;
  }

  /**
   * Get HTML files that have changed since the last commit
   * Filters the changed files to only include .html files in pages directory and index.html
   * Excludes /public directory since those are generated files from markdown processing
   */
  static getChangedHtmlFiles(
    pagesDirectory: string = "source/site/pages",
    indexFile: string = "source/site/index.html"
  ): string[] {
    const changedFiles = this.getChangedFiles();
    const changedHtmlFiles: string[] = [];

    for (const file of changedFiles) {
      // Skip files in public directory (these are generated by markdown processor)
      if (file.startsWith("public/")) {
        continue;
      }

      // Check if it's an HTML file in the pages directory
      if (file.endsWith(".html") && file.startsWith(pagesDirectory)) {
        const absolutePath = join(process.cwd(), file);
        if (existsSync(absolutePath)) {
          changedHtmlFiles.push(absolutePath);
        }
      }
      // Also check for index.html
      else if (file === indexFile) {
        const absolutePath = join(process.cwd(), file);
        if (existsSync(absolutePath)) {
          changedHtmlFiles.push(absolutePath);
        }
      }
    }

    return changedHtmlFiles;
  }

  /**
   * Check if there are any uncommitted changes in the repository
   */
  static hasUncommittedChanges(): boolean {
    if (!this.isGitRepository()) {
      return false;
    }

    try {
      const output = execSync("git status --porcelain", {
        encoding: "utf8",
        stdio: ["ignore", "pipe", "ignore"],
      }).trim();

      return output.length > 0;
    } catch {
      return false;
    }
  }

  /**
   * Get repository status information
   */
  static getRepositoryStatus(): {
    isGitRepo: boolean;
    currentBranch: string | null;
    hasUncommittedChanges: boolean;
    changedFiles: string[];
    changedMarkdownFiles: string[];
    changedHtmlFiles: string[];
  } {
    const isGitRepo = this.isGitRepository();

    if (!isGitRepo) {
      return {
        isGitRepo: false,
        currentBranch: null,
        hasUncommittedChanges: false,
        changedFiles: [],
        changedMarkdownFiles: [],
        changedHtmlFiles: [],
      };
    }

    return {
      isGitRepo: true,
      currentBranch: this.getCurrentBranch(),
      hasUncommittedChanges: this.hasUncommittedChanges(),
      changedFiles: this.getChangedFiles(),
      changedMarkdownFiles: this.getChangedMarkdownFiles(),
      changedHtmlFiles: this.getChangedHtmlFiles(),
    };
  }

  /**
   * Log repository status information
   */
  static logRepositoryStatus(): void {
    const status = this.getRepositoryStatus();

    if (!status.isGitRepo) {
      BuildLogger.info(
        "📝 Not a git repository - processing all markdown files"
      );
      return;
    }

    BuildLogger.info(
      `🔧 Git repository detected (branch: ${
        status.currentBranch || "unknown"
      })`
    );

    if (status.hasUncommittedChanges) {
      BuildLogger.info(`📊 Found ${status.changedFiles.length} changed files`);
      if (status.changedMarkdownFiles.length > 0) {
        BuildLogger.info(
          `📝 Found ${status.changedMarkdownFiles.length} changed markdown files:`
        );
        status.changedMarkdownFiles.forEach((file) => {
          const relativePath = relative(process.cwd(), file);
          BuildLogger.info(`  - ${relativePath}`);
        });
      } else {
        BuildLogger.info("📝 No changed markdown files detected");
      }

      if (status.changedHtmlFiles.length > 0) {
        BuildLogger.info(
          `🌐 Found ${status.changedHtmlFiles.length} changed HTML files:`
        );
        status.changedHtmlFiles.forEach((file) => {
          const relativePath = relative(process.cwd(), file);
          BuildLogger.info(`  - ${relativePath}`);
        });
      } else {
        BuildLogger.info("🌐 No changed HTML files detected");
      }
    } else {
      BuildLogger.info("✨ No uncommitted changes detected");
    }
  }
}
